### ISSUE TITLE
Plugin incompatibility

### ISSUE THREAD

**Issue by Ottokarder** [wielebenwir/commonsbooking#557] opened 2021-03-10 14:40 UTC
I have tried to include commonsbooking in my Wordpress application. I ended up with 404 Errors as soon as I touched the book articel button.

Problems seems to be that the as well installed Events Manager Plug in does interfere with the commonsbooking Plug in

As soon as I deactivate the Events Manager Plug in Commons Booking Plug in starts performing well.   

Has anybody similar experiences and konws a way of overcomming this trap?

**Comment by Ottokarder** [comment] 2021-03-10 18:14
Yes, this is the one. I'm using Version 5.9.11.3 and have on top the "Events als csv exportieren" by Sven Hinse actual version 1.2.1

**Comment by chriwen** [comment] 2021-03-12 09:26
@Ottokarder thank you for reporting this issue. we have it on our todolist with high priority. It seems that events manager plugin is manipulation the urls but we need to analyse further what exacty is causing this error. We will keep you updated in this this ticket.

**Comment by markus-mw** [comment] 2021-03-14 13:01
@Ottokarder , @chriwen : Status: The problem seems to be that, the plugin does some things with permalinks configuration. I'm trying to find a way to let them work together.

**Comment by chriwen** [comment] 2021-05-10 11:38
@markus-mw ein weiterer User berichtet von gleichem Problem mit Events Manager. Kannst du nochmal prüfen, ob es eventuell doch eine Lösung gibt?

**Comment by chriwen** [comment] 2022-04-07 12:05
we are closing this issue as we cannot solve it. It is a problem caused by the other plugin.

**Comment by hansmorb** [comment] 2022-05-11 09:35
Das Problem scheint aus der query var "location" zu stammen, da beide Plugins anscheinend die gleiche query var registrieren. Vielleicht sollten wir nach dem Prinzip "der klügere gibt nach" unsere query vars cb-location statt einfach nur location usw. nennen. Ein bei mir funktionierender Fix liegt im Branch bugfix/issue-557 . 

Wahrscheinlich wäre es besser, die Query Vars in eine Konstante auszulagern damit es nicht manuell an so vielen Orten geändert werden muss, wusste nur nicht wohin damit.

Ich habe die query var absichtlich nicht commonsbooking_location usw. genannt, damit die URLs nicht zu lang werden.

**Closed** 2022-06-06 11:30 UTC
Labels: bug
